// All the words: cases, suspect categories, evidence, hiding spots and riddles.
// Everything here is original writing, tuned to be read aloud to 5–12 year olds.

export const MASCOT = { name: 'Chief Inspector Hoot', icon: '🦉' };

export const DIFFICULTIES = {
  rookie: {
    id: 'rookie',
    label: 'Rookie Detective',
    ages: 'Ages 5–7',
    blurb: 'Everything about every suspect is on their card. Each clue crosses someone off.',
    clues: [4, 6],
    maxCards: 6,
  },
  junior: {
    id: 'junior',
    label: 'Junior Inspector',
    ages: 'Ages 8–10',
    blurb: 'Rooms are known, but outfits or snacks must be worked out. Codes guard each hiding spot.',
    clues: [5, 8],
    maxCards: 7,
  },
  master: {
    id: 'master',
    label: 'Master Sleuth',
    ages: 'Ages 11+ and grown-ups',
    blurb: 'A full logic grid. Nothing is given away. Ciphers, including pigpen.',
    clues: [7, 12],
    maxCards: 8,
  },
};

export const CASES = {
  cookies: {
    id: 'cookies',
    icon: '🍪',
    title: 'The Case of the Vanished Cookies',
    item: 'the last chocolate-chip cookies',
    itemShort: 'cookies',
    container: 'the cookie jar',
    hook: 'At exactly 3:15 this afternoon, someone lifted the lid of {container}, and {item} disappeared. Only crumbs and a guilty silence remain.',
  },
  remote: {
    id: 'remote',
    icon: '📺',
    title: 'The Case of the Missing Remote',
    item: 'the TV remote',
    itemShort: 'remote',
    container: 'its spot on the sofa arm',
    hook: 'Just before movie night, {item} vanished from {container}. Without it, the whole house is doomed to watch the weather channel forever.',
  },
  cake: {
    id: 'cake',
    icon: '🎂',
    title: 'The Great Birthday Cake Caper',
    item: 'the biggest slice of birthday cake',
    itemShort: 'cake',
    container: 'the party plate',
    hook: 'The candles were counted. The plates were set. But when the lights came on, {item} was gone from {container}, and only a smear of frosting was left behind.',
  },
  teddy: {
    id: 'teddy',
    icon: '🧸',
    title: 'The Mystery of the Missing Teddy',
    item: 'Captain Snuggles, the bravest teddy bear in the house',
    itemShort: 'teddy',
    container: 'the pillow fort',
    hook: 'Captain Snuggles was on guard duty in {container}. At bedtime, the fort was empty. A teddy does not just wander off. Or does it?',
  },
  socks: {
    id: 'socks',
    icon: '🧦',
    title: 'The Case of the Sock Snatcher',
    item: 'every single left sock',
    itemShort: 'socks',
    container: 'the laundry basket',
    hook: 'This morning, {container} was full of socks. Tonight, {item} has vanished. The right socks are very upset about it.',
  },
  coins: {
    id: 'coins',
    icon: '🪙',
    title: 'The Pirate Gold Heist',
    item: 'the jar of chocolate pirate coins',
    itemShort: 'pirate gold',
    container: 'the top shelf',
    hook: 'Arr! {item} was hidden safely on {container}. Now the shelf is bare, and there is a trail of gold foil wrappers. Somebody in this house is a pirate.',
  },
  icecream: {
    id: 'icecream',
    icon: '🍦',
    title: 'The Ice-Cream Heist',
    item: 'the last ice-cream bar',
    itemShort: 'ice cream',
    container: 'the freezer',
    hook: 'Someone opened {container} and took {item}. Detectives must move fast. This evidence is melting!',
  },
  crayon: {
    id: 'crayon',
    icon: '🖍️',
    title: 'The Case of the Golden Crayon',
    item: 'the famous Golden Crayon',
    itemShort: 'Golden Crayon',
    container: 'the art box',
    hook: 'There is only one Golden Crayon, and it lives in {container}. Today the box was opened and {item} was gone. Art in this house may never be the same.',
  },
};

// The case types unlocked without a Pro pass.
export const FREE_CASES = ['cookies', 'remote'];

export const SUSPECT_KINDS = {
  person: { label: 'Person', icons: ['👩', '👨', '👵', '👴', '👧', '👦', '🧑', '👶', '🧔', '👱‍♀️', '👩‍🦱', '👨‍🦲'] },
  pet: { label: 'Pet', icons: ['🐶', '🐱', '🐰', '🐹', '🐦', '🐢', '🐠', '🦎', '🐴', '🐔'] },
  toy: { label: 'Toy', icons: ['🧸', '🤖', '🦖', '🪆', '🦄', '🐉', '🚂', '🎎', '🪀', '🧩'] },
};

export const KNOWN_FOR = {
  person: [
    'Claims to be "just looking" in the fridge.',
    'Suspiciously good at hide-and-seek.',
    'Has a laugh you can hear from space.',
    'Says "five more minutes" and means an hour.',
    'Always knows where the snacks are hidden.',
    'Has been caught humming while tiptoeing.',
    'Owns more mugs than anyone needs.',
    'Once "borrowed" the last yogurt. Allegedly.',
    'Can fall asleep sitting up.',
    'Tells the same joke every single day.',
    'Walks very quietly in socks.',
    'Knows every word to every song.',
  ],
  pet: [
    'Can hear a snack bag open from three rooms away.',
    'Professional napper with a very busy schedule.',
    'Has never once said sorry.',
    'Sits on things the moment you need them.',
    'Stares at walls like they know a secret.',
    'Moves silently. Too silently.',
    'Gives innocent eyes on demand.',
    'Has a secret stash somewhere. Probably.',
    'Believes every sandwich is for sharing.',
    'Was seen near the kitchen. Again.',
  ],
  toy: [
    'Never blinks. Ever.',
    'Is always somewhere slightly different in the morning.',
    'Has seen everything from the top of the shelf.',
    'Keeps very quiet under questioning.',
    'Has a smile that is a little too calm.',
    'Was left under the bed once and never forgot it.',
    'Knows all the secrets of the toy box.',
    'Very good at pretending to be just a toy.',
  ],
};

export const CONFESSIONS = {
  person: [
    'I only meant to take ONE little look at {item}... and then my hands just kept going!',
    'I was going to share! Eventually. Probably. Okay, maybe not.',
    'I was testing the house security. You all failed. Also, I got {itemShort}.',
    'It was an emergency. A very important, very delicious emergency.',
    'I thought nobody would notice. I forgot we have DETECTIVES in this house!',
    'In my defence, {item} looked lonely.',
  ],
  pet: [
    'Woof... I mean... it smelled amazing. What was I supposed to do?',
    'I am a creature of the wild. The wild needed {itemShort}.',
    'You left it right there. At nose height. That is basically an invitation.',
    'I was hiding it for safekeeping. In a place I have now forgotten.',
    'I saw you looking at it, so I got it first. Obviously.',
  ],
  toy: [
    'Toys come alive at night. Everyone knows this. And toys need {itemShort} too.',
    'I have been sitting still for YEARS. I deserved {item}!',
    'It was a secret toy-box mission. The other toys made me do it.',
    'Shh. I was building a secret fort, and {item} was the most important part.',
  ],
};

const ON_ROOMS = ['Porch', 'Balcony', 'Staircase', 'Stairs', 'Roof', 'Deck', 'Patio'];
const inRoom = (v) => `${ON_ROOMS.includes(v.name) ? 'on' : 'in'} the ${v.name}`;

// Suspect categories. Each value has a short name, an icon for the notebook grid,
// "tags" for group evidence, and a physical trace the thief would leave behind.
export const CATEGORY_POOL = {
  wearing: {
    id: 'wearing',
    label: 'Wearing',
    question: 'What were they wearing?',
    icon: '👕',
    values: [
      { key: 'scarf', name: 'a red scarf', the: 'the red scarf', icon: '🧣', tags: ['warm', 'red'], trace: 'a fluffy red thread' },
      { key: 'cap', name: 'a blue cap', the: 'the blue cap', icon: '🧢', tags: ['head', 'blue'], trace: 'a blue cap tag' },
      { key: 'socks', name: 'green stripy socks', the: 'the green stripy socks', icon: '🧦', tags: ['feet', 'green'], trace: 'a green sock fuzzball' },
      { key: 'raincoat', name: 'a yellow raincoat', the: 'the yellow raincoat', icon: '🧥', tags: ['warm', 'yellow'], trace: 'a shiny yellow button' },
      { key: 'pajamas', name: 'purple pajamas', the: 'the purple pajamas', icon: '🛌', tags: ['warm', 'purple'], trace: 'a purple pajama thread' },
      { key: 'bowtie', name: 'an orange bow tie', the: 'the orange bow tie', icon: '🎀', tags: ['fancy', 'orange'], trace: 'a tiny orange ribbon' },
      { key: 'sunglasses', name: 'pink sunglasses', the: 'the pink sunglasses', icon: '🕶️', tags: ['head', 'fancy', 'pink'], trace: 'a pink sunglasses screw' },
      { key: 'boots', name: 'muddy wellies', the: 'the muddy wellies', icon: '👢', tags: ['feet'], trace: 'a big muddy boot print' },
      { key: 'cowboy', name: 'a cowboy hat', the: 'the cowboy hat', icon: '🤠', tags: ['head'], trace: 'a piece of hat straw' },
      { key: 'cape', name: 'a superhero cape', the: 'the superhero cape', icon: '🦸', tags: ['fancy', 'red'], trace: 'a scrap of shiny cape fabric' },
    ],
    groups: {
      warm: { found: 'Warm, woolly fibres were caught on the door handle.', none: 'No woolly fibres anywhere, not even one.', thief: 'the thief was wearing something warm and cosy', notThief: 'the thief was NOT wearing anything warm and cosy' },
      head: { found: 'Something on the thief\'s head bumped a low shelf and left a mark.', none: 'The low shelf has no bump marks at all.', thief: 'the thief was wearing something on their head', notThief: 'the thief had nothing on their head' },
      feet: { found: 'Strange, special footprints cross the floor.', none: 'The footprints are plain bare-foot or ordinary.', thief: 'the thief had something special on their feet', notThief: 'the thief had nothing special on their feet' },
      fancy: { found: 'A sprinkle of party glitter sparkles by the scene.', none: 'Not one speck of party glitter was found.', thief: 'the thief was dressed up fancy', notThief: 'the thief was NOT dressed up fancy' },
      red: { found: 'A tiny red fibre was snagged on a corner.', none: 'Every fibre at the scene is checked: none of them are red.', thief: 'the thief was wearing something red', notThief: 'the thief was NOT wearing anything red' },
    },
    is: (S, v) => `${S} was wearing ${v.name}.`,
    not: (S, v) => `${S} was NOT wearing ${v.name}.`,
    either: (S, v, w) => `${S} was wearing either ${v.name} or ${w.name}.`,
    holder: (v) => `whoever wore ${v.the}`,
    thief: (v) => `the thief was wearing ${v.name}`,
    notThief: (v) => `the thief was NOT wearing ${v.name}`,
  },
  snack: {
    id: 'snack',
    label: 'Snack',
    question: 'What were they munching?',
    icon: '🍿',
    values: [
      { key: 'popcorn', name: 'popcorn', icon: '🍿', tags: ['crunchy'], trace: 'popcorn crumbs' },
      { key: 'banana', name: 'a banana', icon: '🍌', tags: ['fruit', 'yellow'], trace: 'a slippery banana string' },
      { key: 'cheese', name: 'cheese cubes', icon: '🧀', tags: ['yellow'], trace: 'a nibble of cheese' },
      { key: 'carrots', name: 'carrot sticks', icon: '🥕', tags: ['crunchy', 'veg'], trace: 'an orange carrot crumb' },
      { key: 'jellybeans', name: 'jelly beans', icon: '🍬', tags: ['sweet'], trace: 'a sticky jelly bean' },
      { key: 'crackers', name: 'crackers', icon: '🍘', tags: ['crunchy'], trace: 'cracker crumbs' },
      { key: 'grapes', name: 'grapes', icon: '🍇', tags: ['fruit', 'sweet'], trace: 'a squashed grape' },
      { key: 'pretzels', name: 'pretzels', icon: '🥨', tags: ['crunchy'], trace: 'a few grains of pretzel salt' },
      { key: 'blueberries', name: 'blueberries', icon: '🫐', tags: ['fruit', 'sweet'], trace: 'a purple blueberry smudge' },
      { key: 'cucumber', name: 'cucumber slices', icon: '🥒', tags: ['veg'], trace: 'a cool cucumber seed' },
    ],
    groups: {
      crunchy: { found: 'Crunchy crumbs are scattered all over the floor.', none: 'The floor is spotless: not a single crunchy crumb.', thief: 'the thief was munching something crunchy', notThief: 'the thief was NOT munching anything crunchy' },
      fruit: { found: 'A sticky, fruity fingerprint was left on the lid.', none: 'The lid was tested: no fruit juice at all.', thief: 'the thief was eating fruit', notThief: 'the thief was NOT eating fruit' },
      sweet: { found: 'There is a sugary sticky patch right by the scene.', none: 'Nothing at the scene is sticky or sugary.', thief: 'the thief was eating something sweet', notThief: 'the thief was NOT eating anything sweet' },
      veg: { found: 'A little bit of vegetable was dropped nearby.', none: 'No trace of vegetables anywhere near the scene.', thief: 'the thief was snacking on vegetables', notThief: 'the thief was NOT snacking on vegetables' },
      yellow: { found: 'A yellow food smudge is on the handle.', none: 'The handle is clean: no yellow smudges.', thief: 'the thief was eating something yellow', notThief: 'the thief was NOT eating anything yellow' },
    },
    is: (S, v) => `${S} was munching ${v.name}.`,
    not: (S, v) => `${S} was NOT munching ${v.name}.`,
    either: (S, v, w) => `${S} was munching either ${v.name} or ${w.name}.`,
    holder: (v) => `whoever was munching ${v.name}`,
    thief: (v) => `the thief was munching ${v.name}`,
    notThief: (v) => `the thief was NOT munching ${v.name}`,
  },
  doing: {
    id: 'doing',
    label: 'Doing',
    question: 'What were they doing?',
    icon: '🎲',
    values: [
      { key: 'comic', name: 'reading a comic', icon: '📖', tags: ['quiet'], trace: 'a torn corner of a comic page' },
      { key: 'nap', name: 'taking a nap', icon: '😴', tags: ['quiet'], trace: 'a pillow feather' },
      { key: 'humming', name: 'humming a song', icon: '🎵', tags: ['noisy'], trace: 'a scribbled music note' },
      { key: 'jigsaw', name: 'doing a jigsaw puzzle', icon: '🧩', tags: ['quiet'], trace: 'one lost jigsaw piece' },
      { key: 'plants', name: 'watering the plants', icon: '🪴', tags: ['messy'], trace: 'a trail of water drips' },
      { key: 'blocks', name: 'building with blocks', icon: '🧱', tags: ['messy'], trace: 'a tiny toy block' },
      { key: 'drawing', name: 'drawing pictures', icon: '🖍️', tags: ['messy', 'quiet'], trace: 'crayon smudges' },
      { key: 'dancing', name: 'practising dance moves', icon: '💃', tags: ['noisy'], trace: 'scuffs from spinning feet' },
      { key: 'drum', name: 'playing the drum', icon: '🥁', tags: ['noisy'], trace: 'a drum sticker' },
      { key: 'bubbles', name: 'blowing bubbles', icon: '🫧', tags: ['messy'], trace: 'a soapy bubble ring' },
    ],
    groups: {
      quiet: { found: 'The neighbour says it was totally silent just before it happened.', none: 'The neighbour heard a racket right before it happened.', thief: 'the thief had been doing something quiet', notThief: 'the thief had NOT been doing anything quiet' },
      noisy: { found: 'The neighbour heard a racket right before it happened.', none: 'The neighbour says it was totally silent just before it happened.', thief: 'the thief had been doing something noisy', notThief: 'the thief had NOT been doing anything noisy' },
      messy: { found: 'Messy smudges were found on the handle.', none: 'The handle is perfectly clean: no messy smudges.', thief: 'the thief had been doing something messy', notThief: 'the thief had NOT been doing anything messy' },
    },
    is: (S, v) => `${S} was ${v.name}.`,
    not: (S, v) => `${S} was NOT ${v.name}.`,
    either: (S, v, w) => `${S} was either ${v.name} or ${w.name}.`,
    holder: (v) => `whoever was ${v.name}`,
    thief: (v) => `the thief had been ${v.name}`,
    notThief: (v) => `the thief had NOT been ${v.name}`,
  },
  where: {
    id: 'where',
    label: 'Room',
    question: 'Where were they?',
    icon: '🚪',
    // Values are built from the family's own rooms at generation time.
    values: [],
    groups: {},
    is: (S, v) => `${S} was ${inRoom(v)}.`,
    not: (S, v) => `${S} was NOT ${inRoom(v)}.`,
    either: (S, v, w) => `${S} was either ${inRoom(v)} or ${inRoom(w)}.`,
    holder: (v) => `whoever was ${inRoom(v)}`,
    thief: (v) => `the thief had just come from the ${v.name}`,
    notThief: (v) => `the thief had NOT come from the ${v.name}`,
  },
};

export const ROOM_OPTIONS = [
  { name: 'Kitchen', icon: '🍳' },
  { name: 'Living Room', icon: '🛋️' },
  { name: 'Bedroom', icon: '🛏️' },
  { name: 'Bathroom', icon: '🛁' },
  { name: 'Dining Room', icon: '🍽️' },
  { name: 'Hallway', icon: '🚪' },
  { name: 'Garden', icon: '🌷' },
  { name: 'Garage', icon: '🚗' },
  { name: 'Balcony', icon: '🌇' },
  { name: 'Study', icon: '📚' },
  { name: 'Laundry Room', icon: '🧺' },
  { name: 'Playroom', icon: '🧸' },
  { name: 'Staircase', icon: '🪜' },
  { name: 'Porch', icon: '🏡' },
  { name: 'Attic', icon: '📦' },
];

export const ROOM_TRACES = {
  Kitchen: 'a dusting of flour on their footprints',
  Garden: 'fresh grass on the carpet',
  Bathroom: 'a whiff of bubble bath',
  Garage: 'a smudge of bicycle oil',
  Bedroom: 'a fuzzy blanket hair',
  'Living Room': 'a sofa-cushion crumb',
  Balcony: 'a leaf blown in from outside',
  'Laundry Room': 'a warm whiff of clean washing',
  Playroom: 'a tiny sticker stuck to a shoe',
  Attic: 'a cobweb on a sleeve',
  Study: 'a paperclip dropped on the floor',
  Porch: 'a bit of doormat fluff',
};

// Hiding spots. Keywords are what the codes spell out; riddles are the hint for
// the spot. All chosen to be safe (no ovens, washing machines, high shelves).
export const SPOTS = [
  { id: 'cushion', label: 'under a sofa cushion', room: 'Living Room', keyword: 'CUSHION', riddle: 'I am soft and square, and you sit on me. Lift me up to see what you can see.' },
  { id: 'pillow', label: 'under a pillow', room: 'Bedroom', keyword: 'PILLOW', riddle: 'At night your head rests on my back. Look underneath me for the next track.' },
  { id: 'shoe', label: 'inside a shoe', room: 'Hallway', keyword: 'SHOE', riddle: 'I have a tongue but cannot talk, and I go with you when you walk.' },
  { id: 'doormat', label: 'under the doormat', room: 'Porch', keyword: 'DOORMAT', riddle: 'Everybody wipes their feet on me. Peek beneath and you will see.' },
  { id: 'fruitbowl', label: 'under the fruit bowl', room: 'Kitchen', keyword: 'FRUIT', riddle: 'Apples, bananas, oranges too. Look under the bowl for your next clue.' },
  { id: 'toybox', label: 'in the toy box', room: 'Playroom', keyword: 'TOYBOX', riddle: 'I am full of fun and games. Dig inside among the names.' },
  { id: 'book', label: 'inside a book on the shelf', room: 'Study', keyword: 'BOOK', riddle: 'I have a spine but no bones, and many pages but no phones.' },
  { id: 'sockdrawer', label: 'in the sock drawer', room: 'Bedroom', keyword: 'SOCKS', riddle: 'Pairs of twins who keep your toes warm live in here in a jumbled swarm.' },
  { id: 'table', label: 'taped under the table', room: 'Dining Room', keyword: 'TABLE', riddle: 'I have four legs but never walk. I hold your dinner while you talk. Look underneath!' },
  { id: 'laundry', label: 'in the laundry basket', room: 'Laundry Room', keyword: 'BASKET', riddle: 'Dirty clothes are thrown in me. Dig through, if you dare, and see!' },
  { id: 'teapot', label: 'inside the teapot (empty and cold!)', room: 'Kitchen', keyword: 'TEAPOT', riddle: 'I am short and stout, with a handle and a spout.' },
  { id: 'coatpocket', label: 'in a coat pocket', room: 'Hallway', keyword: 'COAT', riddle: 'I keep you warm when it is cold. Check my pockets, if you are bold.' },
  { id: 'boot', label: 'inside a boot', room: 'Hallway', keyword: 'BOOT', riddle: 'I splash in puddles and stomp in mud. Look down inside me, detective bud.' },
  { id: 'plantpot', label: 'beside a plant pot', room: 'Balcony', keyword: 'PLANT', riddle: 'I drink water but have no mouth, and I grow up instead of south.' },
  { id: 'bathtub', label: 'in the (dry!) bathtub', room: 'Bathroom', keyword: 'BATH', riddle: 'Bubbles and ducks and splashes galore. Climb in and look, but not on the floor!' },
  { id: 'toothbrush', label: 'next to the toothbrushes', room: 'Bathroom', keyword: 'TOOTHBRUSH', riddle: 'Twice a day I scrub your smile. Your next clue has been here a while.' },
  { id: 'cereal', label: 'behind the cereal box', room: 'Kitchen', keyword: 'CEREAL', riddle: 'Crunchy flakes for breakfast time. Look behind the box to find the rhyme.' },
  { id: 'underbed', label: 'under the bed', room: 'Bedroom', keyword: 'BED', riddle: 'Monsters are said to live beneath me, but only a clue is waiting, you see.' },
  { id: 'umbrella', label: 'in the umbrella stand', room: 'Hallway', keyword: 'UMBRELLA', riddle: 'When rain comes down I open wide. Look where I stand, the clue is inside.' },
  { id: 'petbed', label: "in the pet's bed", room: 'Living Room', keyword: 'PETBED', riddle: 'A furry friend curls up in me. Sniff around, and you will see.' },
  { id: 'pencilcase', label: 'in a pencil case', room: 'Study', keyword: 'PENCIL', riddle: 'Pens and pencils sleep inside. Zip me open, nothing to hide.' },
  { id: 'tissuebox', label: 'in the tissue box', room: 'Living Room', keyword: 'TISSUE', riddle: 'Achoo! Bless you! Pull one out. Your next clue is here, no doubt.' },
  { id: 'lunchbox', label: 'in a lunchbox', room: 'Kitchen', keyword: 'LUNCHBOX', riddle: 'I go to school with sandwiches inside. Open my lid, and look inside.' },
  { id: 'picture', label: 'behind a picture frame', room: 'Living Room', keyword: 'PICTURE', riddle: 'I hold a smile that never moves. Peek behind me for the proof.' },
  { id: 'rug', label: 'under the rug', room: 'Living Room', keyword: 'RUG', riddle: 'I lie on the floor all day and night. Lift my corner to find what is right.' },
  { id: 'mailbox', label: 'in the mailbox', room: 'Porch', keyword: 'MAIL', riddle: 'Letters and parcels come to me. What arrived today? Go and see!' },
  { id: 'bikebasket', label: 'in the bike basket', room: 'Garage', keyword: 'BIKE', riddle: 'Two wheels, two pedals, and a bell that goes ring. Look in my basket for the next thing.' },
  { id: 'watering', label: 'next to the watering can', room: 'Garden', keyword: 'WATERING', riddle: 'I have a spout and give plants a drink. Look beside me. What do you think?' },
  { id: 'bench', label: 'under the garden chair', room: 'Garden', keyword: 'CHAIR', riddle: 'Outside I wait for someone to sit. Look under me, you will find it.' },
  { id: 'towel', label: 'folded in a towel', room: 'Bathroom', keyword: 'TOWEL', riddle: 'I get wetter the more I dry. Unfold me gently, and do not cry!' },
  { id: 'fridge', label: 'on the fridge door (under a magnet)', room: 'Kitchen', keyword: 'FRIDGE', riddle: 'I am cold inside and stick-on outside. Under a magnet the clue will hide.' },
  { id: 'stairs', label: 'on the bottom stair', room: 'Staircase', keyword: 'STAIRS', riddle: 'I go up and I go down, but I never move around.' },
  { id: 'napkin', label: 'folded in a napkin', room: 'Dining Room', keyword: 'NAPKIN', riddle: 'I wipe your mouth when you are done. Unfold me for some clue-finding fun.' },
  { id: 'toolbox', label: 'on top of the toolbox (closed!)', room: 'Garage', keyword: 'TOOLS', riddle: 'Hammers and screws are kept in me. Look on my lid, not inside, you see.' },
  { id: 'deskdrawer', label: 'in the desk drawer', room: 'Study', keyword: 'DESK', riddle: 'Homework is done on top of me. Pull out my drawer and you will see.' },
  { id: 'clotheshanger', label: 'hanging in the wardrobe', room: 'Bedroom', keyword: 'WARDROBE', riddle: 'Your clothes hang out in me all day. Open my doors and look this way.' },
];

export const DETECTIVE_TITLES = {
  rookie: 'Rookie Detective',
  junior: 'Junior Inspector',
  master: 'Master Sleuth',
};
